### ISSUE TITLE
To a correct & consise README for RAP.

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/RAP#88]
We want our software to be readily available for anyone who is interested. The README file should have clear instructions on how to do that. Currently, the instructions are either too verbose, incomplete or even wrong. Let's fix that!

I suggest the following sections should be in the README file:

- [ ] A short(!) introduction about the intention of RAP.
- [ ] A Getting started section. The **only** purpose of this section is to bring RAP to the fingertips of the reader.  No elaboration about the why. 
  - A Prerequisites section, telling you need Docker. That's it. 
  - A consise list of instructions. Happy flow only.
  - A description of a test, so that the user can easily tell that she is fine.
- [ ] A walkthru of an example script.
- [ ] Further reading. This is a list of links to point the user to whatever we think could be of interest.
- [ ] A troubleshoot section. Yes, that's right: As a separate section! This is the place where we want to put extra instructions for the cases where users still fail to get started. This section might grow over time, as we get reports about edge cases. Having this as a separate section helps keeping the `Getting started` section as short as we can.

**Comment by hanjoosten** [comment]
As I am currently strugling to get things up and running, I suggest I will test the instructions. Hopefully @stefjoosten and @Michiel-s will be so kind to edit the instructions in a way that we can close this issue.

**Comment by hanjoosten** [comment]
The `git clone` command points to a non-existing repo.

**Comment by hanjoosten** [comment]
I have started a new branch, fixing the non-existing repo. @stefjoosten and @Michiel-s , please push your commits to that branch a.s.a.p. as soon as you modify it, so we can colaborate on it easily.

**Comment by hanjoosten** [comment]
Running from the branch, following the current instructions there, I end up with a white screen, what is not right, I suppose: 

![image](https://user-images.githubusercontent.com/1159672/97112816-b92dae80-16e6-11eb-94d6-561048a7a5b4.png)

**Comment by hanjoosten** [comment]
I still get the white screen. If I manually go to `http://localhost/#/admin/installer`, I can reinstall the database. Pressing the (initially red) button, it instantaniously changes to the green button. There is no error message in the screen, but the speed of it suggests that nothing worthwile has happend.  

In the log, I see a message about not being able to connect with the database. 

~~~
rap4-db                    | 2020-11-03T11:15:46.018919200Z 2020-11-03 11:15:46 36 [Warning] Access denied for user 'ampersand'@'172.20.0.3' (using password: YES)
~~~

**Comment by hanjoosten** [comment]
~~~
rap4                       | 2020-11-03T11:22:36.699219100Z 172.18.0.2 - - [03/Nov/2020:11:22:36 +0000] "GET / HTTP/1.1" 200 1026 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36"
rap4                       | 2020-11-03T11:22:36.739908300Z 172.18.0.2 - - [03/Nov/2020:11:22:36 +0000] "GET /app/dist/polyfill.min.js HTTP/1.1" 200 33165 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36"
rap4                       | 2020-11-03T11:22:36.744198500Z 172.18.0.2 - - [03/Nov/2020:11:22:36 +0000] "GET /app/dist/project.min.js?-1987550075462258213 HTTP/1.1" 200 22094 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36"
rap4                       | 2020-11-03T11:22:36.762079800Z 172.18.0.2 - - [03/Nov/2020:11:22:36 +0000] "GET /app/ext/AceEditor/lib/ace/src-min-noconflict/ace.js HTTP/1.1" 200 99194 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36"
rap4                       | 2020-11-03T11:22:36.824978700Z 172.18.0.2 - - [03/Nov/2020:11:22:36 +0000] "GET /app/images/logos/logo-ou.png HTTP/1.1" 304 125 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36"
rap4                       | 2020-11-03T11:22:37.051208400Z [2020-11-03 11:22:37] APPLICATION.INFO: Loading configuration from /var/www/src/Ampersand/Misc/defaultSettings.yaml [] {"request_id":"9b61203e7f","ip":"172.18.0.2","method":"GET","url":"/api/v1/app/navbar"}
rap4                       | 2020-11-03T11:22:37.053543000Z [2020-11-03 11:22:37] APPLICATION.INFO: Loading settings from Ampersand compiler [] {"request_id":"9b61203e7f","ip":"172.18.0.2","method":"GET","url":"/api/v1/app/navbar"}
rap4                       | 2020-11-03T11:22:37.053948200Z [2020-11-03 11:22:37] APPLICATION.INFO: Loading configuration from /var/www/config/project.yaml [] {"request_id":"9b61203e7f","ip":"172.18.0.2","method":"GET","url":"/api/v1/app/navbar"}
rap4                       | 2020-11-03T11:22:37.054966800Z [2020-11-03 11:22:37] APPLICATION.INFO: Loading env settings [] {"request_id":"9b61203e7f","ip":"172.18.0.2","method":"GET","url":"/api/v1/app/navbar"}
rap4-db                    | 2020-11-03T11:22:37.062165600Z 2020-11-03 11:22:37 38 [Warning] Access denied for user 'ampersand'@'172.20.0.3' (using password: YES)
rap4                       | 2020-11-03T11:22:37.064776600Z [2020-11-03 11:22:37] APPLICATION.CRITICAL: Uncaught exception/error: 'Cannot connect to the database' Stacktrace: #0 /var/www/bootstrap/framework.php(115): Ampersand\Plugs\MysqlDB\MysqlDB->__construct('db', 'ampersand', 'somepasswordher...', 'rap4', Object(Monolog\Logger), false, false) #1 /var/www/public/api/v1/index.php(16): require_once('/var/www/bootst...') #2 {main} [] {"request_id":"9b61203e7f","ip":"172.18.0.2","method":"GET","url":"/api/v1/app/navbar"}
rap4                       | 2020-11-03T11:22:37.064777400Z [2020-11-03 11:22:37] APPLICATION.CRITICAL: Uncaught exception/error: 'Cannot connect to the database' Stacktrace: #0 /var/www/bootstrap/framework.php(115): Ampersand\Plugs\MysqlDB\MysqlDB->__construct('db', 'ampersand', 'somepasswordher...', 'rap4', Object(Monolog\Logger), false, false) #1 /var/www/public/api/v1/index.php(16): require_once('/var/www/bootst...') #2 {main} [] {"request_id":"9b61203e7f","ip":"172.18.0.2","method":"GET","url":"/api/v1/app/navbar"}
rap4                       | 2020-11-03T11:22:37.065175200Z 172.18.0.2 - - [03/Nov/2020:11:22:37 +0000] "GET /api/v1/app/navbar HTTP/1.1" 200 282 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36"
~~~

**Comment by hanjoosten** [comment]
Ok. minor step forward: It appeared that I had old volumes still available. I got rid of them (Something for the Troubleshoot section). Now I get somewhat further.

**Comment by hanjoosten** [comment]
Now I get a red error message in the screen:
![image](https://user-images.githubusercontent.com/1159672/98165830-d7658c80-1ee6-11eb-914e-66ccc506f651.png)

If I check the logs, it says that the Database rap4 doesn't exist, which is strange.

~~~
han@C7865606:~/hanGit/RAP$ docker-compose logs
Attaching to rap4, enroll, phpmyadmin, rap_dummy-student-prototype_1, traefik, rap4-db
enroll                     | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
enroll                     | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
enroll                     | [Wed Nov 04 20:32:51.283879 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.4.9 configured -- resuming normal operations
enroll                     | [Wed Nov 04 20:32:51.283930 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
phpmyadmin                 | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.20.0.3. Set the 'ServerName' directive globally to suppress this message
phpmyadmin                 | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.20.0.3. Set the 'ServerName' directive globally to suppress this message
phpmyadmin                 | [Wed Nov 04 20:32:51.334418 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.4.11 configured -- resuming normal operations
phpmyadmin                 | [Wed Nov 04 20:32:51.334486 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
dummy-student-prototype_1  | 2020-11-04 20:32:49.485118: [debug] Reading internal file PrototypeContext.adl
dummy-student-prototype_1  | 2020-11-04 20:32:49.500430: [debug] Reading internal file Interfaces.adl
dummy-student-prototype_1  | 2020-11-04 20:32:49.502394: [debug] Reading internal file Interfaces.ifc
dummy-student-prototype_1  | 2020-11-04 20:32:49.503731: [debug] Reading internal file Navbar.adl
dummy-student-prototype_1  | 2020-11-04 20:32:49.508832: [debug] Reading internal file Navbar.ifc
dummy-student-prototype_1  | 2020-11-04 20:32:49.510949: [debug] Reading internal file Roles.adl
dummy-student-prototype_1  | 2020-11-04 20:32:49.511970: [info] Reading file /script.adl
dummy-student-prototype_1  | /script.adl:1:1 error:
dummy-student-prototype_1  |   unexpected end of input
dummy-student-prototype_1  |   expecting keyword "CONTEXT"
dummy-student-prototype_1  | 2020-11-04 20:32:49.512611: [error] ExitFailure 10
traefik                    | time="2020-11-04T20:32:49Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.toml"
rap4-db                    | 2020-11-04 20:32:49+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.4.15+maria~focal started.
rap4-db                    | 2020-11-04 20:32:49+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
rap4-db                    | 2020-11-04 20:32:49+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.4.15+maria~focal started.
rap4-db                    | 2020-11-04 20:32:50+00:00 [Note] [Entrypoint]: Initializing database files
rap4-db                    |
rap4-db                    |
rap4-db                    | PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
rap4-db                    | To do so, start the server, then issue the following commands:
rap4-db                    |
rap4-db                    | '/usr/bin/mysqladmin' -u root password 'new-password'
rap4-db                    | '/usr/bin/mysqladmin' -u root -h  password 'new-password'
rap4-db                    |
rap4-db                    | Alternatively you can run:
rap4-db                    | '/usr/bin/mysql_secure_installation'
rap4-db                    |
rap4-db                    | which will also give you the option of removing the test
rap4-db                    | databases and anonymous user created by default.  This is
rap4-db                    | strongly recommended for production servers.
rap4-db                    |
rap4-db                    | See the MariaDB Knowledgebase at http://mariadb.com/kb or the
rap4-db                    | MySQL manual for more instructions.
rap4-db                    |
rap4-db                    | Please report any problems at http://mariadb.org/jira
rap4-db                    |
rap4-db                    | The latest information about MariaDB is available at http://mariadb.org/.
rap4-db                    | You can find additional information about the MySQL part at:
rap4-db                    | http://dev.mysql.com
rap4-db                    | Consider joining MariaDB's strong and vibrant community:
rap4-db                    | https://mariadb.org/get-involved/
rap4-db                    |
rap4-db                    | 2020-11-04 20:32:54+00:00 [Note] [Entrypoint]: Database files initialized
rap4-db                    | 2020-11-04 20:32:54+00:00 [Note] [Entrypoint]: Starting temporary server
rap4-db                    | 2020-11-04 20:32:54+00:00 [Note] [Entrypoint]: Waiting for server startup
rap4-db                    | 2020-11-04 20:32:54 0 [Note] mysqld (mysqld 10.4.15-MariaDB-1:10.4.15+maria~focal) starting as process 119 ...
rap4-db                    | 2020-11-04 20:32:54 0 [Note] InnoDB: Using Linux native AIO
rap4-db                    | 2020-11-04 20:32:54 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
rap4-db                    | 2020-11-04 20:32:54 0 [Note] InnoDB: Uses event mutexes
rap4-db                    | 2020-11-04 20:32:54 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
rap4-db                    | 2020-11-04 20:32:54 0 [Note] InnoDB: Number of pools: 1
rap4-db                    | 2020-11-04 20:32:54 0 [Note] InnoDB: Using SSE2 crc32 instructions
rap4-db                    | 2020-11-04 20:32:54 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
rap4-db                    | 2020-11-04 20:32:54 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
rap4-db                    | 2020-11-04 20:32:54 0 [Note] InnoDB: Completed initialization of buffer pool
rap4-db                    | 2020-11-04 20:32:54 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
rap4-db                    | 2020-11-04 20:32:54 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
rap4-db                    | 2020-11-04 20:32:54 0 [Note] InnoDB: Creating shared tablespace for temporary tables
rap4-db                    | 2020-11-04 20:32:54 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
rap4-db                    | 2020-11-04 20:32:54 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
rap4-db                    | 2020-11-04 20:32:54 0 [Note] InnoDB: 10.4.15 started; log sequence number 60967; transaction id 21
rap4-db                    | 2020-11-04 20:32:54 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
rap4-db                    | 2020-11-04 20:32:54 0 [Note] Plugin 'FEEDBACK' is disabled.
rap4-db                    | 2020-11-04 20:32:54 0 [Warning] 'user' entry 'root@da8c2f9b6129' ignored in --skip-name-resolve mode.
rap4-db                    | 2020-11-04 20:32:54 0 [Warning] 'proxies_priv' entry '@% root@da8c2f9b6129' ignored in --skip-name-resolve mode.
rap4-db                    | 2020-11-04 20:32:54 0 [Note] InnoDB: Buffer pool(s) load completed at 201104 20:32:54
rap4-db                    | 2020-11-04 20:32:54 0 [Note] Reading of all Master_info entries succeeded
rap4-db                    | 2020-11-04 20:32:54 0 [Note] Added new Master_info '' to hash table
rap4-db                    | 2020-11-04 20:32:54 0 [Note] mysqld: ready for connections.
rap4-db                    | Version: '10.4.15-MariaDB-1:10.4.15+maria~focal'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  mariadb.org binary distribution
rap4-db                    | 2020-11-04 20:32:55+00:00 [Note] [Entrypoint]: Temporary server started.
rap4-db                    | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
rap4-db                    | Warning: Unable to load '/usr/share/zoneinfo/leapseconds' as time zone. Skipping it.
rap4-db                    | Warning: Unable to load '/usr/share/zoneinfo/tzdata.zi' as time zone. Skipping it.
rap4-db                    | 2020-11-04 20:32:58 10 [Warning] 'proxies_priv' entry '@% root@da8c2f9b6129' ignored in --skip-name-resolve mode.
rap4-db                    | 2020-11-04 20:32:58+00:00 [Note] [Entrypoint]: Creating user ampersand
rap4-db                    |
rap4-db                    | 2020-11-04 20:32:58+00:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/01_grant_ampersand.sql
rap4-db                    |
rap4-db                    |
rap4-db                    | 2020-11-04 20:32:58+00:00 [Note] [Entrypoint]: Stopping temporary server
rap4-db                    | 2020-11-04 20:32:58 0 [Note] mysqld (initiated by: root[root] @ localhost []): Normal shutdown
rap4-db                    | 2020-11-04 20:32:58 0 [Note] Event Scheduler: Purging the queue. 0 events
rap4-db                    | 2020-11-04 20:32:58 0 [Note] InnoDB: FTS optimize thread exiting.
rap4-db                    | 2020-11-04 20:32:58 0 [Note] InnoDB: Starting shutdown...
rap4-db                    | 2020-11-04 20:32:58 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
rap4-db                    | 2020-11-04 20:32:58 0 [Note] InnoDB: Buffer pool(s) dump completed at 201104 20:32:58
rap4-db                    | 2020-11-04 20:33:01 0 [Note] InnoDB: Shutdown completed; log sequence number 60976; transaction id 22
rap4-db                    | 2020-11-04 20:33:01 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
rap4-db                    | 2020-11-04 20:33:01 0 [Note] mysqld: Shutdown complete
rap4-db                    |
rap4-db                    | 2020-11-04 20:33:01+00:00 [Note] [Entrypoint]: Temporary server stopped
rap4-db                    |
rap4-db                    | 2020-11-04 20:33:01+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.rap4-db                    |
rap4-db                    | 2020-11-04 20:33:01 0 [Note] mysqld (mysqld 10.4.15-MariaDB-1:10.4.15+maria~focal) starting as process 1 ...
rap4-db                    | 2020-11-04 20:33:01 0 [Note] InnoDB: Using Linux native AIO
rap4-db                    | 2020-11-04 20:33:01 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
rap4-db                    | 2020-11-04 20:33:01 0 [Note] InnoDB: Uses event mutexes
rap4-db                    | 2020-11-04 20:33:01 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
rap4-db                    | 2020-11-04 20:33:01 0 [Note] InnoDB: Number of pools: 1
rap4-db                    | 2020-11-04 20:33:01 0 [Note] InnoDB: Using SSE2 crc32 instructions
rap4-db                    | 2020-11-04 20:33:01 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
rap4-db                    | 2020-11-04 20:33:01 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
rap4-db                    | 2020-11-04 20:33:01 0 [Note] InnoDB: Completed initialization of buffer pool
rap4-db                    | 2020-11-04 20:33:01 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
rap4-db                    | 2020-11-04 20:33:02 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
rap4-db                    | 2020-11-04 20:33:02 0 [Note] InnoDB: Creating shared tablespace for temporary tables
rap4-db                    | 2020-11-04 20:33:02 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
rap4-db                    | 2020-11-04 20:33:02 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
rap4-db                    | 2020-11-04 20:33:02 0 [Note] InnoDB: 10.4.15 started; log sequence number 60976; transaction id 21
rap4-db                    | 2020-11-04 20:33:02 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
rap4-db                    | 2020-11-04 20:33:02 0 [Note] Plugin 'FEEDBACK' is disabled.
rap4-db                    | 2020-11-04 20:33:02 0 [Note] Server socket created on IP: '::'.
rap4-db                    | 2020-11-04 20:33:02 0 [Warning] 'proxies_priv' entry '@% root@da8c2f9b6129' ignored in --skip-name-resolve mode.
rap4-db                    | 2020-11-04 20:33:02 0 [Note] InnoDB: Buffer pool(s) load completed at 201104 20:33:02
rap4-db                    | 2020-11-04 20:33:02 0 [Note] Reading of all Master_info entries succeeded
rap4-db                    | 2020-11-04 20:33:02 0 [Note] Added new Master_info '' to hash table
rap4-db                    | 2020-11-04 20:33:02 0 [Note] mysqld: ready for connections.
rap4-db                    | Version: '10.4.15-MariaDB-1:10.4.15+maria~focal'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
rap4                       | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.4. Set the 'ServerName' directive globally to suppress this message
rap4                       | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.4. Set the 'ServerName' directive globally to suppress this message
rap4                       | [Wed Nov 04 20:32:51.320528 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.4.9 configured -- resuming normal operations
rap4                       | [Wed Nov 04 20:32:51.320598 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
rap4                       | 172.18.0.2 - - [04/Nov/2020:20:35:36 +0000] "GET / HTTP/1.1" 200 1025 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36"
rap4                       | 172.18.0.2 - - [04/Nov/2020:20:35:36 +0000] "GET /app/dist/lib.min.css?-5925652791990574908 HTTP/1.1" 200 20787 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36"
rap4                       | 172.18.0.2 - - [04/Nov/2020:20:35:36 +0000] "GET /app/dist/ampersand.min.css?-5925652791990574908 HTTP/1.1" 200 1820 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36"
rap4                       | 172.18.0.2 - - [04/Nov/2020:20:35:36 +0000] "GET /app/dist/ampersand.min.js?-5925652791990574908 HTTP/1.1" 200 10788 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36"
rap4                       | 172.18.0.2 - - [04/Nov/2020:20:35:36 +0000] "GET /app/dist/project.min.css?-5925652791990574908 HTTP/1.1" 200 224 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36"
rap4                       | 172.18.0.2 - - [04/Nov/2020:20:35:36 +0000] "GET /app/dist/project.min.js?-5925652791990574908 HTTP/1.1" 200 22094 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36"
rap4                       | 172.18.0.2 - - [04/Nov/2020:20:35:36 +0000] "GET /app/dist/lib.min.js?-5925652791990574908 HTTP/1.1" 200 195932 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36"
rap4                       | [2020-11-04 20:35:37] APPLICATION.INFO: Loading configuration from /var/www/src/Ampersand/Misc/defaultSettings.yaml [] {"request_id":"8c716fe41e","ip":"172.18.0.2","method":"GET","url":"/api/v1/app/navbar"}
rap4                       | [2020-11-04 20:35:37] APPLICATION.INFO: Loading settings from Ampersand compiler [] {"request_id":"8c716fe41e","ip":"172.18.0.2","method":"GET","url":"/api/v1/app/navbar"}
rap4                       | [2020-11-04 20:35:37] APPLICATION.INFO: Loading configuration from /var/www/config/project.yaml [] {"request_id":"8c716fe41e","ip":"172.18.0.2","method":"GET","url":"/api/v1/app/navbar"}
rap4                       | [2020-11-04 20:35:37] APPLICATION.INFO: Loading env settings [] {"request_id":"8c716fe41e","ip":"172.18.0.2","method":"GET","url":"/api/v1/app/navbar"}
rap4                       | [2020-11-04 20:35:37] APPLICATION.INFO: Initialize Ampersand application [] {"request_id":"8c716fe41e","ip":"172.18.0.2","method":"GET","url":"/api/v1/app/navbar"}
rap4                       | [2020-11-04 20:35:37] TRANSACTION.INFO: Opening transaction: 617016576 [] {"request_id":"8c716fe41e","ip":"172.18.0.2","method":"GET","url":"/api/v1/app/navbar"}
rap4                       | [2020-11-04 20:35:37] TRANSACTION.WARNING: ExecEngine role 'ExecEngine' configured, but role is not used/defined in &-script [] {"request_id":"8c716fe41e","ip":"172.18.0.2","method":"GET","url":"/api/v1/app/navbar"}
rap4                       | [2020-11-04 20:35:37] TRANSACTION.WARNING: ExecEngine role 'ExecEngine' configured, but role is not used/defined in &-script [] {"request_id":"8c716fe41e","ip":"172.18.0.2","method":"GET","url":"/api/v1/app/navbar"}
rap4                       | [2020-11-04 20:35:37] TRANSACTION.INFO: Request to cancel transaction: 617016576 [] {"request_id":"8c716fe41e","ip":"172.18.0.2","method":"GET","url":"/api/v1/app/navbar"}
rap4                       | [2020-11-04 20:35:37] API.ERROR: Database rap4 does not exist [] {"request_id":"8c716fe41e","ip":"172.18.0.2","method":"GET","url":"/api/v1/app/navbar"}
rap4                       | [2020-11-04 20:35:37] API.ERROR: Database rap4 does not exist [] {"request_id":"8c716fe41e","ip":"172.18.0.2","method":"GET","url":"/api/v1/app/navbar"}
rap4                       | [2020-11-04 20:35:37] PERFORMANCE.INFO: Peak memory used: 4.55 Mb [] {"request_id":"8c716fe41e","ip":"172.18.0.2","method":"GET","url":"/api/v1/app/navbar"}
rap4                       | [2020-11-04 20:35:37] PERFORMANCE.INFO: Execution time  : 0.05 Sec [] {"request_id":"8c716fe41e","ip":"172.18.0.2","method":"GET","url":"/api/v1/app/navbar"}
rap4                       | 172.18.0.2 - - [04/Nov/2020:20:35:37 +0000] "GET /api/v1/app/navbar HTTP/1.1" 500 623 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36"
han@C7865606:~/hanGit/RAP$
~~~

**Comment by hanjoosten** [comment]
If I manually navigate to the installer page, it doesn't install the database. The following lines are appended to the log:

~~~
rap4                       | [2020-11-04 20:47:04] APPLICATION.INFO: Loading configuration from /var/www/src/Ampersand/Misc/defaultSettings.yaml [] {"request_id":"de2e47428f","ip":"172.18.0.2","method":"GET","url":"/api/v1/admin/installer?defaultPop=true"}
rap4                       | [2020-11-04 20:47:04] APPLICATION.INFO: Loading settings from Ampersand compiler [] {"request_id":"de2e47428f","ip":"172.18.0.2","method":"GET","url":"/api/v1/admin/installer?defaultPop=true"}
rap4                       | [2020-11-04 20:47:04] APPLICATION.INFO: Loading configuration from /var/www/config/project.yaml [] {"request_id":"de2e47428f","ip":"172.18.0.2","method":"GET","url":"/api/v1/admin/installer?defaultPop=true"}
rap4                       | [2020-11-04 20:47:04] APPLICATION.INFO: Loading env settings [] {"request_id":"de2e47428f","ip":"172.18.0.2","method":"GET","url":"/api/v1/admin/installer?defaultPop=true"}
rap4                       | [2020-11-04 20:47:04] APPLICATION.INFO: Initialize Ampersand application [] {"request_id":"de2e47428f","ip":"172.18.0.2","method":"GET","url":"/api/v1/admin/installer?defaultPop=true"}
rap4                       | [2020-11-04 20:47:04] TRANSACTION.INFO: Opening transaction: 1976223301 [] {"request_id":"de2e47428f","ip":"172.18.0.2","method":"GET","url":"/api/v1/admin/installer?defaultPop=true"}
rap4                       | [2020-11-04 20:47:04] TRANSACTION.WARNING: ExecEngine role 'ExecEngine' configured, but role is not used/defined in &-script [] {"request_id":"de2e47428f","ip":"172.18.0.2","method":"GET","url":"/api/v1/admin/installer?defaultPop=true"}
rap4                       | [2020-11-04 20:47:04] TRANSACTION.WARNING: ExecEngine role 'ExecEngine' configured, but role is not used/defined in &-script [] {"request_id":"de2e47428f","ip":"172.18.0.2","method":"GET","url":"/api/v1/admin/installer?defaultPop=true"}
rap4                       | [2020-11-04 20:47:04] TRANSACTION.INFO: Request to cancel transaction: 1976223301 [] {"request_id":"de2e47428f","ip":"172.18.0.2","method":"GET","url":"/api/v1/admin/installer?defaultPop=true"}
rap4                       | [2020-11-04 20:47:04] API.ERROR: Database rap4 does not exist [] {"request_id":"de2e47428f","ip":"172.18.0.2","method":"GET","url":"/api/v1/admin/installer?defaultPop=true"}
rap4                       | [2020-11-04 20:47:04] API.ERROR: Database rap4 does not exist [] {"request_id":"de2e47428f","ip":"172.18.0.2","method":"GET","url":"/api/v1/admin/installer?defaultPop=true"}
rap4                       | [2020-11-04 20:47:04] PERFORMANCE.INFO: Peak memory used: 4.55 Mb [] {"request_id":"de2e47428f","ip":"172.18.0.2","method":"GET","url":"/api/v1/admin/installer?defaultPop=true"}
rap4                       | [2020-11-04 20:47:04] PERFORMANCE.INFO: Execution time  : 0.04 Sec [] {"request_id":"de2e47428f","ip":"172.18.0.2","method":"GET","url":"/api/v1/admin/installer?defaultPop=true"}
rap4                       | 172.18.0.2 - - [04/Nov/2020:20:47:04 +0000] "GET /api/v1/admin/installer?defaultPop=true HTTP/1.1" 500 623 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36"

~~~

**Comment by hanjoosten** [comment]
@Michiel-s , the API.ERROR thrown in the log of the previous comment is from the `initExecEngines` function. Could this be related to https://github.com/AmpersandTarski/Ampersand/issues/1045 ?
